<?php

namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        $articles = [
            ['reference' => 'ART-001', 'designation' => 'Lampe H3', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 21, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'N°6', 'designation' => 'GRAISSEUR', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 170, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'N°8', 'designation' => 'GRAISSEUR', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 170, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'N°10', 'designation' => 'GRAISSEUR', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'N°12', 'designation' => 'GRAISSEUR', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 140, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'N°14', 'designation' => 'GRAISSEUR', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 180, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'RAD 140', 'designation' => 'EMPLATRE BIAS RAD 140 TL', 'marque' => 'REMA TIP TOP', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 44, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'RAD 120', 'designation' => 'EMPLATRE BIAS RAD 120 TL', 'marque' => 'REMA TIP TOP', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 23, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'RAD 115', 'designation' => 'EMPLATRE BIAS RAD 115 TL', 'marque' => 'REMA TIP TOP', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 102, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'FRU 1', 'designation' => 'EMPLATRE BIAS FRU 1', 'marque' => 'REMA TIP TOP', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 98, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'FRU 2', 'designation' => 'EMPLATRE BIAS FRU 2', 'marque' => 'REMA TIP TOP', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 103, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-012', 'designation' => 'PQ BAGUETTE BASIC N°3', 'marque' => 'GEKA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-013', 'designation' => 'PQ BAGUETTE BASIC N°4', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 8, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '230*1,9', 'designation' => 'DISQUE 230*1,9', 'marque' => 'ATLAS', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 50, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '115x1,6', 'designation' => 'DISQUE A COUPE 115x1,6', 'marque' => 'NORTON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 50, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '8.8 DIAM 6X50', 'designation' => 'BOULON  8.8 DIAM 6X50', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 100, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '8.8 DIAM 8X50', 'designation' => 'BOULON  8.8 DIAM 8X50', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 90, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '8.8 DIAM 8X80', 'designation' => 'BOULON  8.8 DIAM 8X80', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 55, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '8.8 DIAM 16X80', 'designation' => 'BOULON  8.8 DIAM 16X80', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 90, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '8.8 DIAM 14X80', 'designation' => 'BOULON  8.8 DIAM 14X80', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 30, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ET1316', 'designation' => 'Boulons asemblage M16*140 T (28*16) F100', 'marque' => 'ET1316_MY', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 8, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '3F5108', 'designation' => 'BOULONS DE LAME NIVELEUSE', 'marque' => 'BYG', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 55, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-023', 'designation' => 'SAC CHIFFON', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-024', 'designation' => 'SCOTCH NOIR', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'PLUS +', 'designation' => 'COSSE  P+', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'MOIN -', 'designation' => 'COSSE M-', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-027', 'designation' => 'SINGLE DE LAVAGE 3T', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-028', 'designation' => 'SINGLE DE LAVAGE 6T', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-029', 'designation' => 'BROSSE METALLIQUE A MAIN', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '-80', 'designation' => 'BROSSE DE LA MEULEUSE', 'marque' => 'JAZ', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-031', 'designation' => 'PISTOLET DE LAVAGE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'UT200A+', 'designation' => 'Multimètre d’électricien', 'marque' => 'UNI-T', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-033', 'designation' => 'BOUCHON RESERVOIRE GASOIL', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '5D9559', 'designation' => 'LAME NIVELEUSE 15 TROUS', 'marque' => 'BYG', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'N381-41089D', 'designation' => 'SABOTS 350', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 8, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-036', 'designation' => 'LOCTIT', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 5, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '703141400', 'designation' => 'COLLE PEINZ', 'marque' => 'REINZ', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-038', 'designation' => 'JUPITER ESSANCE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 5, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-039', 'designation' => 'TIFLON', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 5, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'PRO0000100', 'designation' => 'CYLANDER DE FREIN DOUBLE EFFET RVI', 'marque' => 'PROVIA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '020.186', 'designation' => 'SUPPORT DE RESSORT MAN TGA/F2000 DROITE (0,20.186)', 'marque' => 'SAMPA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 4, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '7PK1035', 'designation' => 'COURROIE MOTEUR', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '8PK1920', 'designation' => 'COURROIE MOTEUR MAN', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'XKBH-03315', 'designation' => 'COURROIE MOTEUR HYUNDAI', 'marque' => 'HYUNDAI', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'XKBH-01869', 'designation' => 'COURROIE MOTEUR  HYUNDAI', 'marque' => 'HYUNDAI', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-046', 'designation' => 'RACCORD RAPIDE 6MM', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 30, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-047', 'designation' => 'RACCORD RAPIDE 8MM', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 70, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-048', 'designation' => 'RACCORD RAPIDE 10MM', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 49, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-049', 'designation' => 'RACCORD RAPIDE 12MM', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 28, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-050', 'designation' => 'RACCORD RAPIDE 14MM', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 8, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-051', 'designation' => 'RACCORD RAPIDE 16MM', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 9, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1987302863', 'designation' => 'LAMPE H7', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 45, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1987302862', 'designation' => 'LAMPE H4', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 40, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1987302861', 'designation' => 'LAMPE H3', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 20, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1987302510', 'designation' => 'LAMPE R5W', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 71, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1987302701', 'designation' => 'LAMPE P21W', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1987302866', 'designation' => 'LAMPE PY21W', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 35, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-058', 'designation' => 'PHARE SECOURS LED', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-059', 'designation' => 'POMPE HYDRAULIQUE 110L', 'marque' => 'KAZEL', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '85.145', 'designation' => 'ARRÊt D\'HUILE', 'marque' => 'FEBI', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 5, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '4.20545', 'designation' => 'ARRÊt D\'HUILE', 'marque' => 'SPARE PARTS', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '975524838', 'designation' => 'ARRÊt D\'HUILE', 'marque' => 'REN-PAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-063', 'designation' => 'FLAPS H131 15.5/17.5/16.00/18.00-25', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 4, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '14,00-24', 'designation' => 'CHAMBRE A AIR 14,00-24', 'marque' => 'KABAT', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 6, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '9001', 'designation' => 'INTEREUR DE VALVE P', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 100, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'VMF.V3.22.1', 'designation' => 'Valve Tuables Métal Pour Camion PL-V3.20.', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 50, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'V3-20-10', 'designation' => 'VALVE MÉTALLIQUE METRIC CAMION BUS AGRICOLE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 28, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '81,25101-6738', 'designation' => 'Feux d\'optique MAN Droite', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '95,281', 'designation' => 'Guide en V  MAN', 'marque' => 'SAMPA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '81.52155-0048', 'designation' => 'CARTOUCHE DESSICCATEUR DAIR', 'marque' => 'MAN', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 6, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-071', 'designation' => 'CARTOUCHE DESSICCATEUR DAIR (STOCK MORT )', 'marque' => 'RENAULT', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 6, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '22.0671.0', 'designation' => 'PLAQUETTE DE FREIN IVECO DAILY AV', 'marque' => 'METELLI', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 6, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '526-9052', 'designation' => 'Durite supérieur et inférieur en caoutchouc  345GC', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-074', 'designation' => 'MANOMETRE OXYGENE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '022,456--01', 'designation' => 'CAME DE FREIN MAN AVANT GH', 'marque' => 'SAMPA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '022,455-01', 'designation' => 'CAME DE FREIN MAN AVANT DR', 'marque' => 'SAMPA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '022,436-01', 'designation' => 'CAME DE FREIN MAN ARRIERE GH', 'marque' => 'SAMPA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '022,441-01', 'designation' => 'CAME DE FREIN MAN ARRIERE DR', 'marque' => 'SAMPA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '637-6650', 'designation' => 'Ventilateur de radiateur', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '32016', 'designation' => 'ROULEMENT', 'marque' => 'SKF', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '860804', 'designation' => 'ALTERNATEUR RVI', 'marque' => 'Prestolite', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '320-3060', 'designation' => 'CAPTEUR DE PRESSION D\'HUILE', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '5801317097', 'designation' => 'filtre d\'air IVECO DAILY', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '496-9841', 'designation' => 'Filtre d\'air', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 7, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'P181056', 'designation' => 'Filtre d\'air  chargeuse 760-S', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'P181056', 'designation' => 'Filtre d\'air', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'P536733', 'designation' => 'Filtre à air pour le groupe électrogène', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '14896991A', 'designation' => 'Filtre hydraulique de reservoire benne', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 4, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '1R-0762', 'designation' => 'FILTER A-FUE', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'HF6317', 'designation' => 'Filtre HYD CHARGEUSE 760-9S', 'marque' => 'FLEETGUARD', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'AF25437', 'designation' => 'Filtre d\'air', 'marque' => 'FLEETGUARD', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'AF25523', 'designation' => 'Filtre d\'air CHARGEUSE 760-9S', 'marque' => 'FLEETGUARD', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '81,61910-0050', 'designation' => 'Filtre Climat MAN', 'marque' => 'MAN', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 15, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '81.08405-0022', 'designation' => 'Filtre d\'air MAN', 'marque' => 'MAN', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 26, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '500-0483', 'designation' => 'Filtre a huile', 'marque' => 'CACATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 35, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'LF9009', 'designation' => 'Filtre a huile', 'marque' => 'FLEETGUARD', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '570-1623', 'designation' => 'Filtre a carburant', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 32, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'P553004', 'designation' => 'Filtre a carburant', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'FS1242', 'designation' => 'Filtre separateur', 'marque' => 'FLEETGUARD', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'P551329', 'designation' => 'Filtre separateur', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'P552073', 'designation' => 'Filtre pour liquide de refroidissement', 'marque' => 'DONALDSON', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '496-9842', 'designation' => 'Filtre à air int', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '580-5439', 'designation' => 'Filtre à air cabine Caterpillar', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 7, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '500-0957', 'designation' => 'Filtre à air cabine Caterpillar', 'marque' => 'CATERPILLAR', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '10', 'designation' => 'Tecalan diamètre 10', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '12', 'designation' => 'Tecalan diamètre 12', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '16', 'designation' => 'Tecalan diamètre 16', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 9, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 1/4', 'designation' => 'Flexible 0,60m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 4, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 1/4', 'designation' => 'Flexible 1,50m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 3/4', 'designation' => 'Flexible 0,30m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 3/4', 'designation' => 'Flexible 0,38m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 3/4', 'designation' => 'Flexible 0,50m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 3/4', 'designation' => 'Flexible 1,15m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 3/4', 'designation' => 'Flexible 1,75m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 3/4', 'designation' => 'Flexible 2,20m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R1 1/2', 'designation' => 'Flexible 0,38m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R2 1/2', 'designation' => 'Flexible 0,50m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'R9 1"', 'designation' => 'Flexible 0,78m', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 1, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-119', 'designation' => 'SILENT BLOC AV MAN TGA 6*4 COTE L2 ENR 3/4 (020.188)', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 0, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-120', 'designation' => 'BUSE DE CHALUMEAU AC 16/10', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 0, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-121', 'designation' => 'GYROPHARE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 15, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-122', 'designation' => 'FLEXIBLES DE GRAISSAGE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 13, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-123', 'designation' => 'FEUX ARRIER', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 0, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-124', 'designation' => 'KLAXONS ARRIERE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 0, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-125', 'designation' => 'ALARME MARCHE ARRIERE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 26, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-126', 'designation' => 'BATTERIERS', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-127', 'designation' => 'FEU ARRIERE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 0, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '66ARXE', 'designation' => 'SABOTS 480', 'marque' => 'VOLVO', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 12, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'FC350 RC', 'designation' => 'SABOTS FUTURA', 'marque' => 'FUTURA', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 7, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-130', 'designation' => 'ROULEAUX DE SOULOFFAN', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 6, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '7.6', 'designation' => 'COLLIER EN PLASTIQUE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 5, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => '4.8', 'designation' => 'COLLIER EN PLASTIQUE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 5, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'M15 12V 1000A', 'designation' => 'BATTERIERS', 'marque' => 'BOSCH', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 2, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-134', 'designation' => 'COLLE DE REPARATION PNEUS', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 3, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-135', 'designation' => 'FLEXIBLE DE SOUFLAGE CABINE', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 10, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-136', 'designation' => 'EMPLAITRE BIAS N04', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 60, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-137', 'designation' => 'EMPLAITRE BIAS N05', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 60, 'stock_min' => 0, 'prix_unitaire' => 0],
            ['reference' => 'ART-138', 'designation' => 'ANTIGEL', 'marque' => '', 'unite' => 'Pièce', 'emplacement' => '', 'stock_initial' => 0, 'stock_min' => 0, 'prix_unitaire' => 0],
        ];

        foreach ($articles as $data) {
            Article::create($data);
        }
    }
}