<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Sortie;
use Illuminate\Database\Seeder;

class SortieSeeder extends Seeder
{
    public function run(): void
    {
        $map = Article::pluck('id', 'designation')->toArray();

        $sorties = [
            ['designation' => 'Filtre a carburant', 'technicien' => '', 'affectation' => 'CHARGEUSES E 48', 'quantite' => 1, 'date' => '2026-01-23'],
            ['designation' => 'Filtre a huile', 'technicien' => '', 'affectation' => 'CHARGEUSES E 48', 'quantite' => 1, 'date' => '2026-01-23'],
            ['designation' => 'Filtre separateur', 'technicien' => '', 'affectation' => 'CHARGEUSES E 48', 'quantite' => 1, 'date' => '2026-01-23'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => 'VERS TRANSPORT', 'quantite' => 1, 'date' => '2026-01-24'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => 'VERS D 183', 'quantite' => 1, 'date' => '2026-01-24'],
            ['designation' => 'CHAMBRE A AIR 14,00-24', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-26'],
            ['designation' => 'FLAPS H131 15.5/17.5/16.00/18.00-25', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-26'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => 'SKRO', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => 'SKRO', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'BOULON  8.8 DIAM 6X50', 'technicien' => '', 'affectation' => 'D69', 'quantite' => 2, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'BOULONS DE LAME NIVELEUSE', 'technicien' => '', 'affectation' => 'NIVELEUSE SDLG', 'quantite' => 4, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => 'PNEUS SECOURE', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => 'PNEUS SECOURE', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => 'PNEUS SECOURE', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => 'PNEUS SECOURE', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => 'D 209', 'quantite' => 1, 'date' => '2026-01-27'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-28'],
            ['designation' => 'DISQUE A COUPE 115x1,6', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-01-28'],
            ['designation' => 'PQ BAGUETTE BASIC N°4', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-28'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-28'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-29'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-29'],
            ['designation' => 'SABOTS 350', 'technicien' => '', 'affectation' => 'CAT E71', 'quantite' => 4, 'date' => '2026-01-29'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-01-30'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-30'],
            ['designation' => 'BOULON  8.8 DIAM 6X50', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-01-31'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-01'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-01'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-01'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-04'],
            ['designation' => 'LAME NIVELEUSE 15 TROUS', 'technicien' => '', 'affectation' => 'HYUNDAI E12', 'quantite' => 2, 'date' => '2026-02-04'],
            ['designation' => 'BOULONS DE LAME NIVELEUSE', 'technicien' => '', 'affectation' => '', 'quantite' => 25, 'date' => '2026-02-04'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 3, 'date' => '2026-02-05'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-02'],
            ['designation' => 'LAME NIVELEUSE 15 TROUS', 'technicien' => '', 'affectation' => 'D212', 'quantite' => 10, 'date' => '2026-02-06'],
            ['designation' => 'LAME NIVELEUSE 15 TROUS', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-07'],
            ['designation' => 'BOULON  8.8 DIAM 6X50', 'technicien' => '', 'affectation' => 'SDLG', 'quantite' => 27, 'date' => '2026-02-07'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-07'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-07'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 5, 'date' => '2026-02-09'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-09'],
            ['designation' => 'CHAMBRE A AIR 14,00-24', 'technicien' => '', 'affectation' => 'LOUTA', 'quantite' => 1, 'date' => '2026-02-10'],
            ['designation' => 'FLAPS H131 15.5/17.5/16.00/18.00-25', 'technicien' => '', 'affectation' => 'LOUTA', 'quantite' => 1, 'date' => '2026-02-10'],
            ['designation' => 'GYROPHARE', 'technicien' => '', 'affectation' => 'E48/E12', 'quantite' => 2, 'date' => '2026-02-10'],
            ['designation' => 'LAME NIVELEUSE 15 TROUS', 'technicien' => '', 'affectation' => 'D183', 'quantite' => 1, 'date' => '2026-02-10'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-11'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-11'],
            ['designation' => 'SABOTS 350', 'technicien' => '', 'affectation' => 'PELLE 350 E64', 'quantite' => 4, 'date' => '2026-02-11'],
            ['designation' => 'GRAISSEUR', 'technicien' => '', 'affectation' => 'E57/E18', 'quantite' => 4, 'date' => '2026-02-11'],
            ['designation' => 'GYROPHARE', 'technicien' => '', 'affectation' => 'CHARGEUSE E22 / PELLE 350 E71 / PELLE 350 E 64 / PELLE 336 E18 / CAMION GASOIL MOBILE', 'quantite' => 5, 'date' => '2026-02-11'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'FEUX ARRIER', 'technicien' => '', 'affectation' => 'CAMION GASOIL MOBILE', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'EMPLATRE BIAS RAD 120 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-12'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'Filtre a huile', 'technicien' => '', 'affectation' => 'VERS VIDANGE GROUPE ELECTROGENE', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'Filtre a carburant', 'technicien' => '', 'affectation' => 'VERS VIDANGE GROUPE ELECTROGENE', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'Filtre a huile', 'technicien' => '', 'affectation' => 'VERS VIDANGE NIVELEUSE E12', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'Filtre a carburant', 'technicien' => '', 'affectation' => 'VERS VIDANGE NIVELEUSE E12', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'Filtre separateur', 'technicien' => '', 'affectation' => 'VERS VIDANGE NIVELEUSE E12', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'BOULONS DE LAME NIVELEUSE', 'technicien' => '', 'affectation' => 'D184/D253/D255', 'quantite' => 9, 'date' => '2026-02-12'],
            ['designation' => 'BOULONS DE LAME NIVELEUSE', 'technicien' => '', 'affectation' => 'D184/D255', 'quantite' => 2, 'date' => '2026-02-12'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-12'],
            ['designation' => 'FEU ARRIERE', 'technicien' => '', 'affectation' => 'E22', 'quantite' => 2, 'date' => '2026-02-13'],
            ['designation' => 'BOULONS DE LAME NIVELEUSE', 'technicien' => '', 'affectation' => 'D213', 'quantite' => 1, 'date' => '2026-02-13'],
            ['designation' => 'BOULONS DE LAME NIVELEUSE', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-13'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-14'],
            ['designation' => 'FLEXIBLES DE GRAISSAGE', 'technicien' => '', 'affectation' => 'POMPE GRAISSE', 'quantite' => 1, 'date' => '2026-02-14'],
            ['designation' => 'SABOTS 480', 'technicien' => '', 'affectation' => 'E49', 'quantite' => 6, 'date' => '2026-02-15'],
            ['designation' => 'VALVE MÉTALLIQUE METRIC CAMION BUS AGRICOLE', 'technicien' => '', 'affectation' => '', 'quantite' => 12, 'date' => '2026-02-15'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-16'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-01-16'],
            ['designation' => 'BATTERIERS', 'technicien' => '', 'affectation' => 'CAMION GASOIL MOBILE', 'quantite' => 2, 'date' => '2026-02-16'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => 'PNEUS SECOURE', 'quantite' => 1, 'date' => '2026-02-16'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => 'PNEUS SECOURE', 'quantite' => 1, 'date' => '2026-02-16'],
            ['designation' => 'BOULON  8.8 DIAM 6X50', 'technicien' => '', 'affectation' => 'E12', 'quantite' => 3, 'date' => '2026-02-17'],
            ['designation' => 'LAMPE H7', 'technicien' => '', 'affectation' => 'D 210', 'quantite' => 4, 'date' => '2026-02-17'],
            ['designation' => 'SABOTS FUTURA', 'technicien' => '', 'affectation' => 'VERS E22', 'quantite' => 7, 'date' => '2026-02-17'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-17'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '207', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '207', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-18'],
            ['designation' => 'BATTERIERS', 'technicien' => '', 'affectation' => 'E22', 'quantite' => 2, 'date' => '2026-02-19'],
            ['designation' => 'LAMPE H7', 'technicien' => '', 'affectation' => 'D206', 'quantite' => 1, 'date' => '2026-02-19'],
            ['designation' => 'LAMPE R5W', 'technicien' => '', 'affectation' => 'D216', 'quantite' => 10, 'date' => '2026-02-19'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-20'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-20'],
            ['designation' => 'LAMPE R5W', 'technicien' => '', 'affectation' => 'VERS D212 - D186', 'quantite' => 10, 'date' => '2026-02-20'],
            ['designation' => 'LAMPE R5W', 'technicien' => '', 'affectation' => 'VERS D203', 'quantite' => 6, 'date' => '2026-02-21'],
            ['designation' => 'LAMPE R5W', 'technicien' => '', 'affectation' => 'VERS ARR D69 - D185', 'quantite' => 10, 'date' => '2026-02-23'],
            ['designation' => 'LAMPE R5W', 'technicien' => '', 'affectation' => 'VERS D216 - D204', 'quantite' => 10, 'date' => '2026-02-24'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 3, 'date' => '2026-02-20'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 2, 'date' => '2026-02-20'],
            ['designation' => 'Valve Tuables Métal Pour Camion PL-V3.20.', 'technicien' => '', 'affectation' => '', 'quantite' => 4, 'date' => '2026-02-20'],
            ['designation' => 'EMPLATRE BIAS FRU 2', 'technicien' => '', 'affectation' => 'VERS D210', 'quantite' => 1, 'date' => '2026-02-20'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-21'],
            ['designation' => 'EMPLATRE BIAS RAD 115 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-21'],
            ['designation' => 'LAMPE H7', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-21'],
            ['designation' => 'SABOTS 350', 'technicien' => '', 'affectation' => 'VERS E71', 'quantite' => 4, 'date' => '2026-02-22'],
            ['designation' => 'DISQUE 230*1,9', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-23'],
            ['designation' => 'EMPLATRE BIAS RAD 140 TL', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-23'],
            ['designation' => 'EMPLATRE BIAS FRU 1', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-23'],
            ['designation' => 'PHARE SECOURS LED', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-23'],
            ['designation' => 'LAMPE H7', 'technicien' => '', 'affectation' => '', 'quantite' => 1, 'date' => '2026-02-23'],
            ['designation' => 'EMPLAITRE BIAS N04', 'technicien' => '', 'affectation' => 'D187 + D218', 'quantite' => 2, 'date' => '2026-02-25'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers chargeuse E22', 'quantite' => 5, 'date' => '2025-08-21'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers chargeuse E48', 'quantite' => 10, 'date' => '2025-08-22'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers pick-up', 'quantite' => 15, 'date' => '2025-08-23'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers 480-E49', 'quantite' => 10, 'date' => '2025-08-24'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers chargeuse E22', 'quantite' => 5, 'date' => '2025-08-25'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers 350-E43', 'quantite' => 10, 'date' => '2025-08-26'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers pick-up', 'quantite' => 10, 'date' => '2025-08-28'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D160', 'quantite' => 5, 'date' => '2025-08-30'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D162', 'quantite' => 5, 'date' => '2025-08-30'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers chargeuse E22', 'quantite' => 5, 'date' => '2025-09-02'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers chargeuse E48', 'quantite' => 5, 'date' => '2025-09-02'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D165', 'quantite' => 7, 'date' => '2025-09-03'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers pick-up', 'quantite' => 10, 'date' => '2025-09-04'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers 350-E64', 'quantite' => 10, 'date' => '2025-09-05'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers Chargeuse E22', 'quantite' => 10, 'date' => '2025-09-07'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers Chargeuse E48', 'quantite' => 10, 'date' => '2025-09-09'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers Niveleuse Hyundai', 'quantite' => 10, 'date' => '2025-09-11'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D118', 'quantite' => 3, 'date' => '2025-09-12'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers D119', 'quantite' => 8, 'date' => '2025-09-13'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers pick-up', 'quantite' => 10, 'date' => '2025-09-16'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers Arr D69', 'quantite' => 10, 'date' => '2025-09-17'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers 480-E57', 'quantite' => 10, 'date' => '2025-09-19'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers D183', 'quantite' => 5, 'date' => '2025-09-22'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers Niveleuse SDLG', 'quantite' => 6, 'date' => '2025-09-24'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers pick-up', 'quantite' => 10, 'date' => '2025-09-26'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers chargeuse E22', 'quantite' => 5, 'date' => '2025-09-29'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vaers Chargeuse E48', 'quantite' => 5, 'date' => '2025-10-01'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers D184', 'quantite' => 4, 'date' => '2025-10-02'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D220', 'quantite' => 2, 'date' => '2025-10-03'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D141', 'quantite' => 8, 'date' => '2025-10-04'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D221', 'quantite' => 2, 'date' => '2025-10-05'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Chargeuse E22', 'quantite' => 5, 'date' => '2025-10-06'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Chargeuse E48', 'quantite' => 5, 'date' => '2025-10-06'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers 336-E26', 'quantite' => 4, 'date' => '2025-10-09'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D224', 'quantite' => 3, 'date' => '2025-10-11'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D205', 'quantite' => 3, 'date' => '2025-10-12'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D207', 'quantite' => 3, 'date' => '2025-10-12'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'Vers D208', 'quantite' => 3, 'date' => '2025-10-12'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'chargeuse E22', 'quantite' => 5, 'date' => '2025-10-13'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers chargeuse E48', 'quantite' => 5, 'date' => '2025-10-13'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers niveleuse hyundai', 'quantite' => 3, 'date' => '2025-10-17'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers niveleuse SDLG', 'quantite' => 4, 'date' => '2025-10-19'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers 350-E43', 'quantite' => 5, 'date' => '2025-10-20'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D219', 'quantite' => 3, 'date' => '2025-10-21'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D218', 'quantite' => 2, 'date' => '2025-10-22'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D183', 'quantite' => 6, 'date' => '2025-10-23'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers D187', 'quantite' => 5, 'date' => '2025-10-24'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers chargeuse E48', 'quantite' => 5, 'date' => '2025-10-25'],
            ['designation' => 'ANTIGEL', 'technicien' => '', 'affectation' => 'vers Chargeuse E22', 'quantite' => 5, 'date' => '2025-10-26'],
        ];

        foreach ($sorties as $data) {
            $articleId = $map[$data['designation']] ?? null;
            if (!$articleId) continue;
            Sortie::create([
                'article_id'  => $articleId,
                'technicien'  => $data['technicien'],
                'affectation' => $data['affectation'],
                'quantite'    => $data['quantite'],
                'date'        => $data['date'],
            ]);
        }
    }
}